<?xml version="1.0"?>
<!-- Author: Luca Obwegs -->
<package format="3">
  <name>balancing_robot_sim</name>
  <version>0.1.0</version>
  <description>Gazebo Harmonic simulation and controllers for a two-wheel balancing robot.</description>
  <maintainer email="luca.obwegs@hilti.com">Luca Obwegs</maintainer>
  <license>GPL-3.0-only</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
